import groovy.json.JsonSlurper
import org.gradle.api.Project
import org.gradle.api.artifacts.component.ProjectComponentIdentifier
import java.nio.charset.StandardCharsets
import java.util.zip.ZipFile
import javax.xml.parsers.DocumentBuilderFactory
import org.w3c.dom.Element

tasks.register("writeOsvReleaseRuntimeLockfile") {
    group = "verification"
    description = "生成 OSV Scanner 使用的 releaseRuntimeClasspath 依赖锁定文件。"

    val outputFile = layout.buildDirectory.file("osv/release-runtime/gradle.lockfile")
    outputs.file(outputFile)

    doLast {
        val releaseRuntimeConfigurationName = "releaseRuntimeClasspath"
        val targetProjects = listOf(
            project(":gson-safe-parser-core"),
            project(":gson-safe-parser-retrofit"),
            project(":demo-app")
        )
        val coordinates = sortedSetOf<String>()

        targetProjects.forEach { targetProject ->
            val configuration = targetProject.configurations.getByName(releaseRuntimeConfigurationName)
            for (component in configuration.incoming.resolutionResult.allComponents) {
                if (component.id is ProjectComponentIdentifier) {
                    continue
                }
                val moduleVersion = component.moduleVersion ?: continue
                coordinates += "${moduleVersion.group}:${moduleVersion.name}:${moduleVersion.version}=$releaseRuntimeConfigurationName"
            }
        }

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("# Generated by ./gradlew writeOsvReleaseRuntimeLockfile.")
                appendLine("# Used by OSV Scanner to audit release runtime dependencies.")
                coordinates.forEach { coordinate -> appendLine(coordinate) }
                appendLine("empty=")
            },
            StandardCharsets.UTF_8
        )
    }
}

tasks.register("verifyMavenLocalPublicationArtifacts") {
    group = "verification"
    description = "验证 Maven local 中的 AAR、POM、sources、javadoc 和 demo release 混淆合并配置。"
    dependsOn(
        ":gson-safe-parser-core:publishToMavenLocal",
        ":gson-safe-parser-retrofit:publishToMavenLocal",
        ":demo-app:assembleRelease"
    )

    doLast {
        val versionValue = project(":gson-safe-parser-core").version.toString()
        val artifactIds = listOf("gson-safe-parser-core", "gson-safe-parser-retrofit")
        artifactIds.forEach { artifactId ->
            val base = mavenLocalArtifactBase(artifactId, versionValue)
            val aar = base.resolveSibling("${base.name}.aar")
            val jar = base.resolveSibling("${base.name}.jar")
            val sourcesJar = base.resolveSibling("${base.name}-sources.jar")
            val javadocJar = base.resolveSibling("${base.name}-javadoc.jar")
            val pom = base.resolveSibling("${base.name}.pom")

            requireFile(aar)
            require(!jar.exists()) { "Unexpected plain jar artifact exists: ${jar.absolutePath}" }
            requireFile(sourcesJar)
            requireFile(javadocJar)
            requireFile(pom)
            require(pomPackaging(pom) == "aar") { "POM packaging must be aar: ${pom.absolutePath}" }

            requireZipEntries(
                aar,
                listOf("classes.jar", "proguard.txt", "META-INF/LICENSE", "META-INF/NOTICE")
            )
            val aarRules = readZipEntry(aar, "proguard.txt")
            listOf(
                "kotlin.Metadata",
                "com.google.gson.Gson",
                "com.google.gson.GsonBuilder",
                "java.util.List hierarchyFactories",
                "com.google.gson.internal.bind.TreeTypeAdapter",
                "com.google.gson.reflect.TypeToken exactType",
                "boolean matchRawType",
                "java.lang.Class hierarchyType",
                "@com.google.gson.annotations.SerializedName <fields>"
            ).forEach { requiredRule ->
                require(aarRules.contains(requiredRule)) {
                    "${aar.absolutePath} proguard.txt misses $requiredRule"
                }
            }
            requireZipEntryMatching(sourcesJar) { entryName -> entryName.endsWith(".kt") }
            requireZipEntries(javadocJar, listOf("index.html"))
        }

        val retrofitPom = mavenLocalArtifactBase("gson-safe-parser-retrofit", versionValue)
            .resolveSibling("gson-safe-parser-retrofit-$versionValue.pom")
        val retrofitModule = mavenLocalArtifactBase("gson-safe-parser-retrofit", versionValue)
            .resolveSibling("gson-safe-parser-retrofit-$versionValue.module")
        requireFile(retrofitModule)
        require(pomDependencyVersion(retrofitPom, "gson-safe-parser-core") == versionValue) {
            "Retrofit POM must depend on gson-safe-parser-core $versionValue"
        }
        require(pomDependencyVersion(retrofitPom, "okhttp") == "4.12.0") {
            "Retrofit POM must depend on okhttp 4.12.0"
        }
        require(pomDependencyVersion(retrofitPom, "okio") == "3.6.0") {
            "Retrofit POM must depend on okio 3.6.0"
        }
        require(pomDependencyScope(retrofitPom, "okhttp") == "runtime") {
            "Retrofit POM must keep okhttp as runtime scope"
        }
        require(pomDependencyScope(retrofitPom, "okio") == "runtime") {
            "Retrofit POM must keep okio as runtime scope"
        }
        require(moduleDependencyVersion(retrofitModule, "runtimeElements", "okhttp") == "4.12.0") {
            "Retrofit module metadata runtimeElements must depend on okhttp 4.12.0"
        }
        require(moduleDependencyVersion(retrofitModule, "runtimeElements", "okio") == "3.6.0") {
            "Retrofit module metadata runtimeElements must depend on okio 3.6.0"
        }
        require(moduleDependencyVersion(retrofitModule, "apiElements", "okhttp") == null) {
            "Retrofit module metadata apiElements must not expose okhttp"
        }
        require(moduleDependencyVersion(retrofitModule, "apiElements", "okio") == null) {
            "Retrofit module metadata apiElements must not expose okio"
        }

        val demoConfig = file("demo-app/build/outputs/mapping/release/configuration.txt")
        requireFile(demoConfig)
        val demoConfiguration = demoConfig.readText()
            listOf(
                "io.github.logan.gsonsafeparser.demo.model.**",
                "kotlin.Metadata",
                "com.google.gson.Gson",
                "com.google.gson.GsonBuilder",
                "java.util.List hierarchyFactories",
                "com.google.gson.internal.bind.TreeTypeAdapter",
                "com.google.gson.reflect.TypeToken exactType",
                "boolean matchRawType",
                "java.lang.Class hierarchyType",
                "@com.google.gson.annotations.SerializedName <fields>"
            ).forEach { requiredRule ->
            require(demoConfiguration.contains(requiredRule)) {
                "${demoConfig.absolutePath} misses $requiredRule"
            }
        }
    }
}

fun Project.mavenLocalArtifactBase(artifactId: String, versionValue: String) =
    file("${System.getProperty("user.home")}/.m2/repository/io/github/logan0817/$artifactId/$versionValue/$artifactId-$versionValue")

fun requireFile(file: java.io.File) {
    require(file.isFile) { "Missing file: ${file.absolutePath}" }
}

fun requireZipEntries(file: java.io.File, entries: List<String>) {
    val entryNames = zipEntryNames(file)
    entries.forEach { entry ->
        require(entryNames.contains(entry)) { "${file.absolutePath} misses $entry" }
    }
}

fun requireZipEntryMatching(file: java.io.File, predicate: (String) -> Boolean) {
    require(zipEntryNames(file).any(predicate)) { "${file.absolutePath} misses expected entry" }
}

fun zipEntryNames(file: java.io.File): List<String> {
    return ZipFile(file).use { zipFile ->
        zipFile.entries().asSequence().map { entry -> entry.name }.toList()
    }
}

fun readZipEntry(file: java.io.File, entryName: String): String {
    return ZipFile(file).use { zipFile ->
        val entry = zipFile.getEntry(entryName)
            ?: error("${file.absolutePath} misses $entryName")
        zipFile.getInputStream(entry).bufferedReader().use { reader -> reader.readText() }
    }
}

fun parsePom(file: java.io.File) =
    DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(file).also { document ->
        document.documentElement.normalize()
    }

fun pomPackaging(file: java.io.File): String? {
    return parsePom(file).documentElement.childText("packaging")
}

fun pomDependencyVersion(file: java.io.File, artifactId: String): String? {
    return pomDependencyChildText(file, artifactId, "version")
}

fun pomDependencyScope(file: java.io.File, artifactId: String): String? {
    return pomDependencyChildText(file, artifactId, "scope") ?: "compile"
}

fun pomDependencyChildText(file: java.io.File, artifactId: String, childName: String): String? {
    val dependencies = parsePom(file).getElementsByTagName("dependency")
    for (index in 0 until dependencies.length) {
        val dependency = dependencies.item(index) as? Element ?: continue
        if (dependency.childText("artifactId") == artifactId) {
            return dependency.childText(childName)
        }
    }
    return null
}

@Suppress("UNCHECKED_CAST")
fun moduleDependencyVersion(file: java.io.File, variantName: String, moduleName: String): String? {
    val module = JsonSlurper().parse(file) as? Map<String, Any?> ?: return null
    val variants = module["variants"] as? List<*> ?: return null
    val variant = variants
        .filterIsInstance<Map<String, Any?>>()
        .firstOrNull { variant ->
            variant.matchesPublicationVariant(variantName)
        }
        ?: return null
    val dependencies = variant["dependencies"] as? List<*> ?: return null
    val dependency = dependencies
        .filterIsInstance<Map<String, Any?>>()
        .firstOrNull { dependency -> dependency["module"] == moduleName }
        ?: return null
    val version = dependency["version"]
    return when (version) {
        is Map<*, *> -> version["requires"] as? String ?: version["strictly"] as? String
        is String -> version
        else -> null
    }
}

@Suppress("UNCHECKED_CAST")
fun Map<String, Any?>.matchesPublicationVariant(variantName: String): Boolean {
    val name = this["name"] as? String
    if (name?.contains(variantName, ignoreCase = true) == true) return true
    val attributes = this["attributes"] as? Map<String, Any?> ?: return false
    val usage = attributes["org.gradle.usage"] as? String ?: return false
    return when (variantName) {
        "apiElements" -> usage == "java-api"
        "runtimeElements" -> usage == "java-runtime"
        else -> false
    }
}

fun Element.childText(tagName: String): String? {
    return getElementsByTagName(tagName).item(0)?.textContent
}
